### ISSUE TITLE
cannot emulate linux/amd64 correctly on m1

### ISSUE THREAD

**Issue by chylli-binary** [abiosoft/colima#395] opened 2022-08-14 15:53 UTC
### Description

commands will not work correctly in debian under emulated linux/amd64 
```
colima start
docker pull --platform linux/amd64 debian
docker run --platform linux/amd64 -it --rm  debian bash
```

```
root@0af6a274c413:/# which which
/usr/bin/which: 0: cannot open which: No such file
root@0af6a274c413:/# ls
bin  boot  dev	etc  home  lib	lib64  media  mnt  opt	proc  root  run  sbin  srv  sys  tmp  usr  var
root@0af6a274c413:/# ls bin
bin  boot  dev	etc  home  lib	lib64  media  mnt  opt	proc  root  run  sbin  srv  sys  tmp  usr  var
root@0af6a274c413:/# cd bin
root@0af6a274c413:/bin# ls
bash   chmod  dash  df	   dnsdomainname  egrep  findmnt  gzexe     ln	   lsblk  mktemp  mountpoint	 pidof	readlink  run-parts  sleep  sync      touch   uname	  wdctl		zcmp	zfgrep	zless
cat    chown  date  dir    domainname	  false  grep	  gzip	    login  mkdir  more	  mv		 pwd	rm	  sed	     stty   tar       true    uncompress  ypdomainname	zdiff	zforce	zmore
chgrp  cp     dd    dmesg  echo		  fgrep  gunzip   hostname  ls	   mknod  mount   nisdomainname  rbash	rmdir	  sh	     su     tempfile  umount  vdir	  zcat		zegrep	zgrep	znew
root@0af6a274c413:/bin# ls /
bash   chmod  dash  df	   dnsdomainname  egrep  findmnt  gzexe     ln	   lsblk  mktemp  mountpoint	 pidof	readlink  run-parts  sleep  sync      touch   uname	  wdctl		zcmp	zfgrep	zless
cat    chown  date  dir    domainname	  false  grep	  gzip	    login  mkdir  more	  mv		 pwd	rm	  sed	     stty   tar       true    uncompress  ypdomainname	zdiff	zforce	zmore
chgrp  cp     dd    dmesg  echo		  fgrep  gunzip   hostname  ls	   mknod  mount   nisdomainname  rbash	rmdir	  sh	     su     tempfile  umount  vdir	  zcat		zegrep	zgrep	znew
root@0af6a274c413:/bin# 
```

`ls` command cannot accept any argument
`which` cannot get correct result.

### Version

Colima Version: HEAD-fc948f8
Lima Version: 0.11.3
Qemu Version: 7.0.0

### Operating System

- [ ] macOS Intel
- [X] macOS M1
- [ ] Linux

### Reproduction Steps

1. colima start
2. docker pull --platform linux/amd64 debian
3. docker run --platform linux/amd64 -it --rm  debian bash
4. ls bin
5. which which

### Expected behaviour

`ls bin` command should list files under /bin directory. but it will list files under `/` root dir
`which which` should print `/usr/bin/which`, but it will print `/usr/bin/which: 0: cannot open which: No such file`

**Comment by ventsislav-georgiev** [comment] 2022-08-22 18:42
I can confirm there is an issue with emulation with latest version (6c4889b).
On macOS M1, running an amd64 image inside k3s crashes on startup and goes into CrashLoop. 

The repro case in the issue is simple enough to check. The latest release v0.4.4 doesn't have that issue.

**Comment by abiosoft** [comment] 2022-08-22 18:50
Thanks for confirming @ventsislav-georgiev.

**Comment by ventsislav-georgiev** [comment] 2022-08-25 19:28
@abiosoft Revering to alpine 3.14.6 seems to fix the emulation.

**Comment by abiosoft** [comment] 2022-09-18 07:34
@ventsislav-georgiev I am reverting it. Thanks.

**Comment by jandubois** [comment] 2022-09-18 10:34
I believe this has been fixed by https://github.com/lima-vm/alpine-lima/pull/82

**Comment by abiosoft** [comment] 2022-09-18 10:53
@jandubois Thanks :) Will verify.

**Closed** 2022-09-18 13:40 UTC
