### ISSUE TITLE
No Internet Connection inside VM / macOS m1 / 0.4.2 Nix version

### ISSUE THREAD

**Issue by tricktron** [abiosoft/colima#344] opened 2022-06-21 10:30 UTC
### Describe the Issue
The DNS resolver inside the Colima VM does not work and I thus have no internet connection at all.

Everything works with Colima 0.3.4 / limactl 0.11.0 / qemu 7.0.0.

#### Colima Version:

What is the output of `colima version`
0.4.2
#### Lima Version:

What is the output of `limactl --version`
0.11.0
#### Qemu Version

What is the output of `qemu-img --version`
7.0.0
### Operating System

- [ ] macOS Intel
- [x] macOS m1 12.4
- [ ] Linux

### To Reproduce

1. `docker pull node:16-alpine` -> Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 192.168.107.1:53: read udp 192.168.5.15:40660->192.168.107.1:53: i/o timeout
2. colima ssh
3. ping google.com -> `bad address 'google.com'`

### Expected behavior

DNS resolver and internet connections work.

### Additional context
Edit: I use the nix package manager to install colima.

Content of /etc/resolv.conf:
`nameserver 192.168.107.1`

Starting Colima with `colima start --dns 1.1.1.1` solves the dns resolution problem and connections work again but VPN does **not**. On 0.3.4 VPN connections work perfectly.

**Comment by abiosoft** [comment] 2022-06-21 13:18
Does starting with `colima start --dns 192.168.5.3` work with your VPN connection?

**Comment by tricktron** [comment] 2022-06-22 10:05
@abiosoft Unfortunately not. I still get the same errors:
- docker pull node:16-alpine -> `Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 192.168.5.3:53: read udp 192.168.5.15:50251->192.168.5.3:53: i/o timeout`
- ping google.com inside vm -> `bad address 'google.com'`

**Comment by abiosoft** [comment] 2022-06-22 11:22
@tricktron are you on any slack channel, can we get to troubleshoot this interactively? Or is there a way I can simulate your VPN environment?

**Comment by tricktron** [comment] 2022-06-22 12:37
> Or is there a way I can simulate your VPN environment?

I don't think so. It is a VPN using the [Citrix Secure Access App](https://apps.apple.com/ch/app/citrix-secure-access/id1338991513?l=en&mt=12) to connect to one of my customers.

However, I think we need to solve the issues step by step:
1. `colima start` without the `--dns` option results in having no connection at all as well. I don't see any address when running `colima ls` either:
![Screenshot 2022-06-22 at 14 30 13](https://user-images.githubusercontent.com/16036882/175029509-c3abb7b1-92ef-40cf-b7b6-9472ee7d0955.png).

Is that a bug or expected?

> are you on any slack channel, can we get to troubleshoot this interactively?
I am not using slack anymore but if you point me to the right direction/channel I can quickly reactivate my account if it helps.

**Comment by abiosoft** [comment] 2022-06-22 13:10
@tricktron I have been able to reproduce the issue, it seems to be specific to Nix version. There is indeed no internet.

**Comment by aaschmid** [comment] 2022-06-22 14:30
@abiosoft: Can I still help to reproduce?

**Comment by abiosoft** [comment] 2022-06-22 16:32
> @abiosoft: Can I still help to reproduce?

Yeah you can, just to ascertain. Thanks.

**Comment by aaschmid** [comment] 2022-06-23 18:15
Have the same issue w/o any VPN. Strangely, I cannot ping any of the ip adresses from `nslookup registry-1.docker.io`, whereas other pings work just normal. Don't know if this is just normal. Just tell me if I can help further...

**Comment by aaschmid** [comment] 2022-06-23 19:15
You are absolutely right, `curl` works just fine on console but not from within `colima ssh` (same as another other connection to the "outside" world)

**Comment by Guwancsayidaliyew** [comment] 2022-06-24 05:42
Sa6

**Comment by Guwancsayidaliyew** [comment] 2022-06-24 05:42
Salowmaleykim

**Comment by Guwancsayidaliyew** [comment] 2022-06-24 05:43
@abiosoft  brother

**Comment by Guwancsayidaliyew** [comment] 2022-06-24 05:45
my brother please send me the intran code

**Comment by abiosoft** [comment] 2022-06-26 15:44
@tricktron do you also have a non-Nix installation of colima on your machine?

**Comment by tricktron** [comment] 2022-06-26 16:14
@abiosoft
I also tried to do the following manually:
- Install go 1.18, lima 0.11 via nix
- run `make build`
- run `make install`

But I get the same problem without any internet connection.

I have noticed that the following changed from 0.3.4 -> 0.4.1
- go 1.17 -> go 1.18
- alpine-lima-0.3.4-1 -> alpine-lima-0.4.2-1
- colima 0.3.4 -> 0.4.1

Where should we search for the error?

Do we know that it works with brew on Macos m1?

**Comment by abiosoft** [comment] 2022-06-26 16:29
The issue I discovered can only be triggered by a mix of Nix and non-Nix installed versions of colima. I am just trying to ascertain if that is your scenario as well. 

Basically some symlinks are generated at `~/.colima/_wrapper` that becomes inaccurate when colima binary resides in multiple locations (which is always the case for Nix). 

It was an oversight from me as I mostly build and run from source.

A fix will soon be out for you to test.

**Comment by tricktron** [comment] 2022-06-26 17:09
> Basically some symlinks are generated at ~/.colima/_wrapper that can become inaccurate when colima binary resides in multiple locations (which is always the case for Nix).

@abiosoft Ah I see, your qemu wrapping here:
https://github.com/abiosoft/colima/blob/3c03f809f984301ac16e966a35dfefd9178bc44c/cmd/colima/main.go#L21-L29

does somehow interfere with nix and its symlinks. Great catch. I'll gladly help you test the fix when it is out:smiley:.

**Comment by abiosoft** [comment] 2022-06-26 19:01
@tricktron can you kindly build from source and try out the `nix-troubleshooting` branch?

**Comment by tricktron** [comment] 2022-06-26 20:21
@abiosoft wow that was quick. I'll test it tomorrow.

**Comment by tricktron** [comment] 2022-06-27 07:23
@abiosoft 
With the current nix code I get the following warning/error during `colima start`:

`WARN[0000] error setting up network dependencies: error at 'preparing network': error occured installing dependencies for 'gvproxy': error locating qemu binaries in PATH: exec: "qemu-system-aarch64": executable file not found in $PATH`

I quickly added the qemu binary to the path and the warning disappeared. However, in both scenarios I still don't have any internet inside the vm.

ls -la $HOME/.colima/_warpper/bin:
- 699aeb7a4c23553fd0a613dfe210dc4ab93f5b59

So no more qemu-* exectuables that point to colima.

What is the intended dependency of qemu for colima? Should it be on the path? What about gvproxy? What is the meaning of `CGO_ENABLED=0`?

**Comment by abiosoft** [comment] 2022-06-27 07:38
@tricktron did you attempt deleting and starting afresh? Or use another profile `colima start <profile-name>`.
Also, can you `colima ssh` and share the output of `ip route`?

> ls -la $HOME/.colima/_warpper/bin
> * 699aeb7a4c23553fd0a613dfe210dc4ab93f5b59

`699aeb7a4c23553fd0a613dfe210dc4ab93f5b59` is actually a directory.

> What is the intended dependency of qemu for colima? Should it be on the path? What about gvproxy? What is the meaning of CGO_ENABLED=0?

* Thanks for point that out it shouldn't need to be in PATH (for Nix), I'll look at that.
* [gvproxy](https://github.com/containers/gvisor-tap-vsock) is an alternate network provider for qemu. 
* `CGO_ENABLED=0` is nothing serious as well, it makes the binary free of C related dependencies, should have been there from the onset.

**Comment by tricktron** [comment] 2022-06-27 08:12
@abiosoft 
> did you attempt deleting and starting afresh? Or use another profile colima start <profile-name>.

Yes I have always run the following before each test run:
- colima delete
- rm -rf $HOME/.lima
- rm -rf $HOME/.colima

> Also, can you colima ssh and share the output of ip route?
```log
iproute
default via 192.168.5.2 dev eth0  metric 202 
172.17.0.0/16 dev docker0 scope link  src 172.17.0.1 
192.168.5.0/24 dev eth0 scope link  src 192.168.5.15
```

**Comment by tricktron** [comment] 2022-06-27 08:21
Maybe this helps:

The created colima executable by nix is not the colima binary but the following shell wrapper file, which then calls the .colima-wrapped binary:
```bash
#! /nix/store/l81df76j5jxr8lymk9zp9af94llkir94-bash-5.1-p16/bin/bash -e
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/1rpmalspdzssrh6165q0wv262vwafhdd-qemu-7.0.0/bin'':'/':'}
PATH='/nix/store/1rpmalspdzssrh6165q0wv262vwafhdd-qemu-7.0.0/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/3ls9sgrz6sq2gx8hpmz9s5h021jhxdrg-lima-0.11.1/bin'':'/':'}
PATH='/nix/store/3ls9sgrz6sq2gx8hpmz9s5h021jhxdrg-lima-0.11.1/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
exec -a "$0" "/nix/store/h0mv4wmk51rbm6nssadg0iinlfdmiw79-colima-0.4.2/bin/.colima-wrapped"  "$@"
```

So I think you can debug this locally if you just replace all nix-paths in this file with your local paths. You can also remove qemu or lima from the path if you want.

My guess is that some env variables for gvproxy get lost on the long indirection way from nix-colima -> .colima-wrapped -> colima -> lima -> qemu.

**Comment by tricktron** [comment] 2022-06-27 09:16
> I am still pretty new to Nix, does this mean that it is better to work off a derivation as that is the only guaranteed way to get this behaviour.

A nix derivation is a package. The nix-shell just provides you with the dependencies of the package.

Developing/debugging a package needs a fork of nixpkgs. See https://nixos.wiki/wiki/Nixpkgs/Create_and_debug_packages.

The result of the colima derivation is the above bash file.

So you can work with that. In other words, it means that if colima works with the above bash file it works with nix. That should also means that if you replace all nix paths in the bash file with local paths, then you should be able to reproduce the no internet error. Could you try that?

**Comment by abiosoft** [comment] 2022-06-28 06:17
Thanks @tricktron  for the heads up, I have successfully reproduced and identified the issue.

Colima wraps qemu binaries to utilise [gvproxy](https://github.com/containers/gvisor-tap-vsock), this is done by overriding the Qemu binaries used by Lima via PATH. However, Nix overrides this behaviour with wrapped binaries and Lima will always use Nix provided Qemu binaries.

There are two approaches.
* Use a custom Lima derivation for Colima on Nix. This is easier and I am leaning towards it.
* Get Lima to support passing additional argument to Qemu, so no workarounds will be needed. This is better, no magic involved. However, it is slower as it will take a while to get the contribution to Lima approved, merged, released and updated on Nix.

**Comment by tricktron** [comment] 2022-06-28 07:34
@abiosoft
Great that you could reproduce it👍. 

I am strong believer in the golden rule of open source: *push fixes upstream* instead of hacking locally around them. So I would go for:

> Get Lima to support passing additional arguments to Qemu, so no workarounds will be needed. This is better, no magic involved. However, it is slower as it will take a while to get the contribution to Lima approved, merged, released and updated on Nix.

In the meantime we could have a look at:
> Use a custom Lima derivation for Colima on Nix. I am leaning towards this.

But before getting into that discussion: Everything worked on nix in version 0.3.4. What new features in 0.4.1 need gvproxy? I see that you introduced a daemon.

Daemons are not handled directly in nix with a derivation but with a nix module (handled by other projects such as [nix-darwin](https://github.com/LnL7/nix-darwin) and [home-manager](https://github.com/nix-community/home-manager), which needs separate integration.

So I would be perfectly fine, if there is a flag `--no-deamon` which just ignores the daemon and gvproxy and uses the old functionality. But that only works if gvproxy is only used for your daemon feature. Is that the case?

**Comment by abiosoft** [comment] 2022-06-28 17:34
@tricktron can you update the `nix-troubleshooting` branch and see if the binary from the [derivation](https://github.com/abiosoft/colima/blob/0ca857b01695f687126796a0c798ec9fa88a9b15/default.nix) has internet access.
You can also simply run `make nix-derivation-shell` to build and drop into the resulting nix-shell.

Thanks as usual.

> But before getting into that discussion: Everything worked on nix in version 0.3.4. What new features in 0.4.1 need gvproxy? I see that you introduced a daemon.

There were complaints of intermittent internet issues in previous versions and gvproxy seems to have provided a better experience. You were probably not affected.

> So I would be perfectly fine, if there is a flag --no-deamon which just ignores the daemon and gvproxy and uses the old functionality. But that only works if gvproxy is only used for your daemon feature. Is that the case?

Yeah, this is being looked at as well. Not the flag per se but a fallback mechanism.

**Comment by tricktron** [comment] 2022-06-29 06:31
@abiosoft 
It works🎉.

Direct access to the `limactl` binary fixes the no internet issue. Note: This already works with `v0.4.1`, so all the changes in your `nix-troubleshooting` branch have no directly visible impact.

I created two prs in nixpkgs to fix this:
- this https://github.com/NixOS/nixpkgs/pull/179521 adds the unwrapped lima binary
- this https://github.com/NixOS/nixpkgs/pull/179522 uses the unwrapped lima binary and fixes the no-internet issue.

I also want to use the new Makefile in the pr. Could you create a new tag/version for it so that I can use it.

@aaschmid Could you help reviewing the prs in nixpkgs?

**Comment by abiosoft** [comment] 2022-06-29 06:37
Yeah, I would still like to merge in the `nix-troubleshooting` branch as more edge cases are now handled and more importantly the [tests are now fixed for nix](https://github.com/NixOS/nixpkgs/blob/f2537a505d45c31fe5d9c27ea9829b6f4c4e6ac5/pkgs/applications/virtualization/colima/default.nix#L31).

**Comment by tricktron** [comment] 2022-06-29 06:44
@abiosoft Sure, go for it👍🏼

**Closed as completed** 2022-06-29 07:02 UTC

**Comment by abiosoft** [comment] 2022-06-29 07:18
> I also want to use the new Makefile in the pr. Could you create a new tag/version for it so that I can use it?

@tricktron here it is https://github.com/abiosoft/colima/releases/tag/v0.4.3. 
Release and release notes will be generated after the CI build is done.

**Comment by abiosoft** [comment] 2022-06-29 17:15
Also initiated the proper fix upstream. https://github.com/lima-vm/lima/issues/932
