### ISSUE TITLE
v0.4.1: x86_64 getting stuck with qemu64 cpu

### ISSUE THREAD

**Issue by sadbuttrue1** [abiosoft/colima#288] opened 2022-05-16 17:40 UTC
Updated colima from 0.3.4 to 0.4.1.
Did `colima delete` and `colima start` (`colima start --arch amd --cpu 4 --memory 4` to be precise).
Got
```
FATA[0642] error starting vm: error at 'creating and starting': exit status 1
```
Here is log after starting:
[serial.log](https://github.com/abiosoft/colima/files/8702084/serial.log)

macOS version 12.3.1
CPU Apple M1 Max
colima version 0.4.1
lima version 0.10.0
qemu version 6.2.0_1

**Comment by abiosoft** [comment] 2022-05-16 17:48
Can you kindly try again with `--verbose` flag specified and share the output.
Also, does it work if you use the default arch for your machine i.e. aarch64 ?

**Comment by sadbuttrue1** [comment] 2022-05-16 17:50
> Can you kindly try again with `--verbose` flag specified and share the output.
> Also, does it work if you use the default arch for your machine i.e. aarch64 ?

Yes, I can try it with `--verbose`. On which stage should I do it? Freshly installed colima, lima and qemu?

I didn't try it with `aarch64` because I need `x86_64`. And `x86_64` was fine with 0.3.4.

**Comment by sadbuttrue1** [comment] 2022-05-16 18:17
Result of `colima start --arch amd --cpu 4 --memory 4 --verbose`:
```
INFO[0000] starting colima
INFO[0000] runtime: docker
INFO[0000] preparing network ...                         context=vm
INFO[0000] creating and starting ...                     context=vm
> msg="Terminal is not available, proceeding without opening an editor"
> msg="Attempting to download the image from \"https://github.com/abiosoft/alpine-lima/releases/download/colima-v0.4.0-5/alpine-lima-clm-3.15.4-x86_64.iso\"" digest="sha512:6ce50a109cc90f537cc0eb363ab938ba10ea690dc59e1f4c0081ecd90907da5fb305ab27a98ebec774e97d41a713f73f0a4e7edc44019a7db134a07181bb8801"
>
> 38.33 MiB / 267.00 MiB (14.36%) ? p/s
> 84.63 MiB / 267.00 MiB (31.70%) 9.26 MiB/s
> 119.52 MiB / 267.00 MiB (44.76%) 9.11 MiB/s
> 159.67 MiB / 267.00 MiB (59.80%) 9.04 MiB/s
> 194.58 MiB / 267.00 MiB (72.88%) 8.91 MiB/s
> 216.72 MiB / 267.00 MiB (81.17%) 8.62 MiB/s
> 241.14 MiB / 267.00 MiB (90.32%) 8.38 MiB/s
> 246.30 MiB / 267.00 MiB (92.25%) 7.91 MiB/s
> 251.24 MiB / 267.00 MiB (94.10%) 7.46 MiB/s
> 261.19 MiB / 267.00 MiB (97.82%) 7.11 MiB/s
> 267.00 MiB / 267.00 MiB (100.00%) 5.59 MiB/stime="2022-05-16T21:06:04+03:00" level=info msg="Downloaded image from \"https://github.com/abiosoft/alpine-lima/releases/download/colima-v0.4.0-5/alpine-lima-clm-3.15.4-x86_64.iso\""
> msg="[hostagent] local user \"evgenii.aslanov\" is not a valid Linux username (must match \"^[a-z_][a-z0-9_-]*$\"); using \"lima\" username instead"
> msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \"/Users/evgenii.aslanov/.lima/colima/serial.log\")"
> msg="SSH Local Port: 54697"
> msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
> msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
> msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
> msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
> msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
> msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
> msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
> msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
> msg="did not receive an event with the \"running\" status"
FATA[0654] error starting vm: error at 'creating and starting': exit status 1
```
[serial.log](https://github.com/abiosoft/colima/files/8702417/serial.log)

**Comment by abiosoft** [comment] 2022-05-16 18:40
Does specifying `--cpu-type qemu64` improve anything ?

**Comment by abiosoft** [comment] 2022-05-16 18:51
@sadbuttrue1  I have been able to reproduce it, using `--cpu-type kvm64` works. Can you kindly confirm if it works for you as well?

I need to figure out why the default config stops working.

**Comment by sadbuttrue1** [comment] 2022-05-16 19:05
@abiosoft, with `qemu64` it did stuck without messages in `serial.log`.
With `colima start --arch amd --cpu 4 --memory 4 --verbose --cpu-type kvm64` it seems to be fine, at least it didn't fail stuck in 10 minutes :)

**Comment by abiosoft** [comment] 2022-05-16 19:14
As a side note, is x86_64 emulation your primary use-case? I would expect the degraded performance to discourage extensive use.

**Comment by sadbuttrue1** [comment] 2022-05-16 19:18
Yes, I'm using it to run https://hub.docker.com/_/microsoft-mssql-server. 
You mean that with the `kvm64` it'll be slower than it was with default params of 0.3.4?

**Comment by abiosoft** [comment] 2022-05-16 19:23
> You mean that with the kvm64 it'll be slower than it was with default params of 0.3.4?

Not at all, it will be similar performance to the default processor. I'm only referring to the fact that emulation is always noticeably slower than native architecture.

**Comment by rfay** [comment] 2022-05-16 19:27
@sadbuttrue1 Do put your "me too" on https://github.com/microsoft/mssql-docker/issues/734 - when they get to that it will make a big difference.

**Comment by sadbuttrue1** [comment] 2022-05-17 05:30
@abiosoft, yes, I know about slowness of emulation. But currently it's the only option for testing with mssql that have full text search feature.

@rfay, thanks, will put!

**Comment by mritd** [comment] 2022-05-17 06:24
same issue here...

<img width="968" alt="image" src="https://user-images.githubusercontent.com/13043245/168742690-82c182c1-e322-4b23-8075-4ea251fe328e.png">

For my use case:

x86 emulation is usually used to test some images that do not provide arm support; or in some cases we need to build x86 docker image to push to a remote server to run it.

**Comment by abiosoft** [comment] 2022-05-17 07:08
@mritd specifying `--cpu-type kvm64` works as seen here https://github.com/abiosoft/colima/issues/288#issuecomment-1128019441 and specifying `--cpu-type Haswell-v4` also works.

Looking at https://github.com/lima-vm/lima/issues/641 I can see the previous default value was `Haswell-v4`, but that was changed a while back since Lima v0.8.2.

**Comment by mritd** [comment] 2022-05-17 07:10
Oh sorry, I forgot to mention... I tested `--cpu-type` and it works fine, just a little slow....

**Comment by abiosoft** [comment] 2022-05-17 07:15
> Oh sorry, I forgot to mention... I tested `--cpu-type` and it works fine, just a little slow....

@mritd you mean it's slower than before?

**Comment by mritd** [comment] 2022-05-17 07:16
@abiosoft Just feeling, I didn't do the full test.

**Comment by oanhnn** [comment] 2022-05-18 03:49
My environment
```
MacBook Air (M1, 2020)
macOS version 12.3.1
CPU Apple M1
colima version 0.4.1
lima version 0.10.0
qemu version 6.2.0_1
```

I got the same error after start and pull some docker image.

```
$ colima start -a x86_64 -c 2 -m 4
$ docker ps
$ docker context ls
$ docker image pull ...
```

But it working fine with `lima` and docker template

```
$ limactl start ~/.lima/docker.yml
$ docker context use lima
$ docker ps
$ docker image pull ...
```

Below is information about the QEMU process.

```
$ ps aux | grep qemu              
oanhnn           36037   6.6 11.9 414593056 1994976 s000  S    10:15AM   1:28.83 qemu-system-x86_64 -m 4096 -cpu qemu64 -machine q35,vmport=off -accel tcg,thread=multi,tb-size=512 -global ICH9-LPC.disable_s3=1 -smp 2,sockets=1,cores=2,threads=1 -drive if=pflash,format=raw,readonly=on,file=/Users/oanhnn/.colima/_wrapper/share/qemu/edk2-x86_64-code.fd -boot order=d,splash-time=0,menu=on -drive file=/Users/oanhnn/.lima/colima/basedisk,media=cdrom,readonly=on -drive file=/Users/oanhnn/.lima/colima/diffdisk,if=virtio -cdrom /Users/oanhnn/.lima/colima/cidata.iso -netdev user,id=net0,net=192.168.5.0/24,dhcpstart=192.168.5.15,hostfwd=tcp:127.0.0.1:60277-:22 -device virtio-net-pci,netdev=net0,mac=52:55:55:09:af:6f -device virtio-rng-pci -display none -device virtio-vga -device virtio-keyboard-pci -device virtio-mouse-pci -parallel none -chardev socket,id=char-serial,path=/Users/oanhnn/.lima/colima/serial.sock,server=on,wait=off,logfile=/Users/oanhnn/.lima/colima/serial.log -serial chardev:char-serial -chardev socket,id=char-qmp,path=/Users/oanhnn/.lima/colima/qmp.sock,server=on,wait=off -qmp chardev:char-qmp -name lima-colima -pidfile /Users/oanhnn/.lima/colima/qemu.pid -netdev socket,id=vlan,fd=3 -device virtio-net-pci,netdev=vlan,mac=5a:94:ef:b2:dd:3c
oanhnn           36036   0.0  0.1 409232816  17760 s000  S    10:15AM   0:00.01 /Users/oanhnn/.colima/_wrapper/bin/qemu-system-x86_64 -m 4096 -cpu qemu64 -machine q35,vmport=off -accel tcg,thread=multi,tb-size=512 -global ICH9-LPC.disable_s3=1 -smp 2,sockets=1,cores=2,threads=1 -drive if=pflash,format=raw,readonly=on,file=/Users/oanhnn/.colima/_wrapper/share/qemu/edk2-x86_64-code.fd -boot order=d,splash-time=0,menu=on -drive file=/Users/oanhnn/.lima/colima/basedisk,media=cdrom,readonly=on -drive file=/Users/oanhnn/.lima/colima/diffdisk,if=virtio -cdrom /Users/oanhnn/.lima/colima/cidata.iso -netdev user,id=net0,net=192.168.5.0/24,dhcpstart=192.168.5.15,hostfwd=tcp:127.0.0.1:60277-:22 -device virtio-net-pci,netdev=net0,mac=52:55:55:09:af:6f -device virtio-rng-pci -display none -device virtio-vga -device virtio-keyboard-pci -device virtio-mouse-pci -parallel none -chardev socket,id=char-serial,path=/Users/oanhnn/.lima/colima/serial.sock,server=on,wait=off,logfile=/Users/oanhnn/.lima/colima/serial.log -serial chardev:char-serial -chardev socket,id=char-qmp,path=/Users/oanhnn/.lima/colima/qmp.sock,server=on,wait=off -qmp chardev:char-qmp -name lima-colima -pidfile /Users/oanhnn/.lima/colima/qemu.pid
oanhnn           36145   0.0  0.0 408628368   1488 s000  R+   10:19AM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox qemu
```

```
$ ps aux | grep qemu
oanhnn           36888   9.0 19.2 414831520 3227456 s000  S    10:36AM   6:45.86 /opt/homebrew/bin/qemu-system-x86_64 -m 4096 -cpu qemu64 -machine q35,vmport=off -accel tcg,thread=multi,tb-size=512 -global ICH9-LPC.disable_s3=1 -smp 4,sockets=1,cores=4,threads=1 -drive if=pflash,format=raw,readonly=on,file=/opt/homebrew/share/qemu/edk2-x86_64-code.fd -boot order=c,splash-time=0,menu=on -drive file=/Users/oanhnn/.lima/docker/diffdisk,if=virtio -cdrom /Users/oanhnn/.lima/docker/cidata.iso -netdev user,id=net0,net=192.168.5.0/24,dhcpstart=192.168.5.15,hostfwd=tcp:127.0.0.1:60700-:22 -device virtio-net-pci,netdev=net0,mac=52:55:55:42:92:4b -device virtio-rng-pci -display none -device virtio-vga -device virtio-keyboard-pci -device virtio-mouse-pci -parallel none -chardev socket,id=char-serial,path=/Users/oanhnn/.lima/docker/serial.sock,server=on,wait=off,logfile=/Users/oanhnn/.lima/docker/serial.log -serial chardev:char-serial -chardev socket,id=char-qmp,path=/Users/oanhnn/.lima/docker/qmp.sock,server=on,wait=off -qmp chardev:char-qmp -name lima-docker -pidfile /Users/oanhnn/.lima/docker/qemu.pid
oanhnn           37144   0.0  0.0 408637584   1792 s000  S+   10:43AM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox qemu
```

**Comment by Meligy** [comment] 2022-05-18 05:15
I have just upgraded too and while the start command worked the 2nd time, any docker command or even `colima list` was just going forever (it actually killed my terminal, seemingly because my prompt, spaceship, gets some docker info, which was resolved by commenting out the prompt from my zsh defaults).

Is there a start command that still works, even if slow? Any additional arguments to pass?

**Comment by Meligy** [comment] 2022-05-18 05:48
This is most of the Dockerfile that seems to break it. It's essentially SQL Server with enabled Free Text Search. It worked just fine with older version of colima, and it has not been modified recently

```dockerfile
# Using non default image as Full-text search support is not included in it
# This image implements https://schwabencode.com/blog/2019/10/27/MSSQL-Server-2017-Docker-Full-Text-Search
# We can implement it ourselves,
#   but our Dockerfile is rebuilt with the local script and the steps in the image very slow.
# It's a specific tag, verifiable at https://hub.docker.com/r/benjaminabt/mssql-fts/tags
FROM benjaminabt/mssql-fts:2019-cu10-ubuntu-2004
ENV ACCEPT_EULA Y

# ENV MSSQL_PID # Does not matter
ENV MSSQL_SA_PASSWORD DoesNotMatter

# Missing from the base image: `mssql-tools`, needs above ACCEPT_EULA env variable set first
# Found via https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15#ubuntu
# The original image does some cleanup, so we have to repeat parts of their script. It's still faster.
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -yq curl apt-transport-https && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | tee /etc/apt/sources.list.d/msprod.list && \
    apt-get update && \
    apt-get install -y mssql-tools unixodbc-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists

# Run SQL Server process
CMD /opt/mssql/bin/sqlservr

# ... File clipped intentionally
```

Once I try to run this (via docker-compose), it hangs:

<img width="1750" alt="image" src="https://user-images.githubusercontent.com/171637/168965882-9e5b52ab-0c3c-4e09-9a3f-476f82708d5f.png">

And from then on any command interacting with colima or docker hangs, even `colima list`....
Wth one lucky exception being `colima delete`.

**Comment by oanhnn** [comment] 2022-05-18 06:01
@Meligy I think you should try with below two ways:

1. Using `--cpu-type` when start a Colima instance.

```
$ colima colima start -a x86_64 -c 4 -m 4 --cpu-type kvm64
$ docker run hello-world
```

Or `--cpu-type Haswell-v4` 

See 

https://github.com/abiosoft/colima/issues/288#issuecomment-1128019441
https://github.com/abiosoft/colima/issues/288#issuecomment-1128495211

2. Using [lima](https://github.com/lima-vm/lima) with docker template (my choice)

```
$ lima start --name=docker https://raw.githubusercontent.com/lima-vm/lima/master/examples/docker.yaml
$ docker context create lima --docker "host=unix:///Users/oanhnn/.lima/docker/sock/docker.sock"
$ docker context use lima
$ docker run hello-world
```

After this issue is fixed, we can use Colima agian 😄

**Comment by abiosoft** [comment] 2022-05-18 10:18
Can you all try the development version with `brew install --HEAD colima`.

If it works fine, a new release will be made.

**Comment by Meligy** [comment] 2022-05-18 11:56
@abiosoft thanks a lot. This does work.

It seems quite slow though. For the above image with this command:
```zsh
colima start --arch x86_64 --cpu 4 --memory 4 --disk 60
```
The extraction time is quite too slow (I don't have a baseline to compare to, but it feels way way slower). Same for running the apt commands in the Dockerfile, and for starting SQL Server and running a handful SQL scripts.

<img width="1750" alt="image" src="https://user-images.githubusercontent.com/171637/169033064-9114b43d-4346-4e69-8151-ec3dc8939d47.png">

However, this is still an improvement over not working at all though.  
Thanks a lot.

**Comment by Meligy** [comment] 2022-05-18 12:21
I also tried the last "released" version (not `--head`), with the following command based on @oanhnn's reply:

```zsh
 colima start --arch x86_64 --cpu 4 --memory 4 --disk 60 --cpu-type Haswell-v4
```

I set `--cpu-type` to `Haswell-v4` to try something different, as looking at latest commit, it seemed `kvm64` was used by `colima` when I didn't specify it in the previous test.

The non-scientific results were pretty comparable times, if not tiny bit slower maybe.

<img width="1750" alt="image" src="https://user-images.githubusercontent.com/171637/169037451-c5361c0f-83a6-4f34-8e06-8725f0ea32ff.png">

I think this makes `--head` the best current option.

**Comment by abiosoft** [comment] 2022-05-19 06:51
can anyone confirm if the latest development version `brew install --HEAD colima` works as desired.

**Closed** 2022-05-19 06:51 UTC

**Comment by Meligy** [comment] 2022-05-19 16:15
@abiosoft thanks heaps for this. It's much better.

I deleted the old one, installed the `--head` version, and created a new one with the following command (no `--cpu-type` to make sure it works without it, and it did work):

```zsh
colima start --arch x86_64 --cpu 4 --memory 4 --disk 60
```

And then my timings were at least 50% less. You can compare this pic with above screenshots:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/171637/169348089-1d794dbd-1e95-4e87-a606-609233cd9bfc.png">

The actual container performance, seems much improved as well, as you see waiting for SQL Server to start and running a. handful small scripts now takes half a minute (last number) instead of 3.5+ minutes.

Thanks again.

**Comment by abiosoft** [comment] 2022-05-19 16:24
@Meligy will push out a new release shortly. Thanks for confirming.

**Comment by abiosoft** [comment] 2022-05-20 06:17
Fix now in stable version https://github.com/abiosoft/colima/releases/tag/v0.4.2

**Comment by Meligy** [comment] 2022-05-20 07:16
Thanks heaps.
