### ISSUE TITLE
How to start with local docker image

### ISSUE THREAD

**Issue by Aikenwu** [abiosoft/colima#1089] opened 2024-08-01 01:42 UTC
### Description

Due to the network limit,  I can't start Colima. It's always a downloading disk image error.
But I can get a docker image from another place.
Can I use a locally downloaded docker image to start Colima?
 
Same as this issue : https://github.com/abiosoft/colima/issues/995

### Version

colima version 0.7.0

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

FATA[0000] colima is not running 

### Reproduction Steps

1.brew install colima
2.brew install docker
3.colima start

### Expected behaviour

I want to config a local docker image to start colima.

**Comment by abiosoft** [comment] 2024-08-03 12:47
Duplicate of #995.

**Closed by abiosoft** 2024-08-03 12:47 UTC

**Comment by abiosoft** [comment] 2024-08-06 21:25
This may be due to https://github.com/abiosoft/colima/issues/1098.

Can you try the current development version? Colima should now resume broken downloads.
