### ISSUE TITLE
0.6.7 - Initialization of base image fails / stuck at "expanding disk" - macOS Intel with vmtype vz and virtioifs

### ISSUE THREAD

**Issue by AndreasA** [abiosoft/colima#930] opened 2023-12-13 13:18 UTC
### Description

After updating to colima 0.6.7 something did not work upon start, so I did the usual

```sh
colima stop
colima delete
colima prune -a

# Even did additionally:
brew remove colima lima qemu
brew install colima
brew autoremove
# reboot and reinstall
```

Then I did a colima start with vm-type vz and virtiofs and the new image failed to load successfully. It got stuck at expanding disk image. After this happened the mac got stuck on shutdown/reboot as well and only a force shutdown worked.

I checked the folder `~/.colima/_lima/colima` and it seems the image conversion might have failed or was missing a step as it was called diffdisk.<random>.tmp instead of just diffdisk.

I tried not specifying the vz type and virtiofs and it started successfully in QEMU and sshfs mode.

I then uninstalled `0.6.7` and manually downloaded `0.6.6`, did a `colima start` there and it worked fine. I then removed the 0.6.6 colima binary and installed 0.6.7 through brew again and now a start works as well. so it seems the issuue is indeed with 0.6.7 and image initialization. maybe the image has a bug?

I originally had 13.x installed and tried the upgrade to 14.x to check if that might solve the issue. it did not, so the issue occured in both scenarios.

### Version

colima version 0.6.7
git commit: ba1be00e9aec47f2c1ffdacfb7e428e465f0b58a

runtime: docker
arch: x86_64
client: v24.0.7
server: v24.0.7

limactl version 0.19.0

### Operating System

- [X] macOS Intel <= 13 (Ventura)
- [X] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [ ] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using macOS Virtualization.Framework
INFO[0000] arch: x86_64
INFO[0000] runtime: docker
INFO[0000] mountType: virtiofs

### Reproduction Steps

see description.

### Expected behaviour

colima starts even after delete on intel mac with 0.6.7

**Comment by AndreasA** [comment] 2023-12-13 15:06
Another user just had the same issue:

```
colima start --cpu 4 --memory 12 --ssh-agent --vm-type vz --mount-type virtiofs
INFO[0000] starting colima
INFO[0000] runtime: docker
INFO[0000] creating and starting ...           context=vm
>
> 1.23 GiB / 3.50 GiB (35.10%) ? p/s
> 1.61 GiB / 3.50 GiB (46.09%) 78.80 MiB/s
> 1.91 GiB / 3.50 GiB (54.52%) 77.61 MiB/s
> 3.03 GiB / 3.50 GiB (86.64%) 87.45 MiB/s
> 3.50 GiB / 3.50 GiB (100.00%) 180.90 MiB/stime=“2023-12-13T16:03:26+01:00” level=info msg=“Expanding to 60GiB”
```

**Comment by AndreasA** [comment] 2023-12-13 15:33
The only solution I found was to temporarily downgrade to 0.6.6, do the start there, then reinstall 0.6.7.

So something like this - probably not all deletions etc. are necessary but to be safe I did them multiple times:

```
colima stop -f
# Reboot macOS - warning most likely macOS will freeze during reboot and require a force shutdown.
colima delete
colima prune -a
rm -rf ~/.lima
rm -rf ~/.colima
rm -rf ~/Library/Caches/colima
rm -rf ~/Library/Caches/lima
brew uninstall colima
curl -o ~/colima -L https://github.com/abiosoft/colima/releases/download/v0.6.6/colima-Darwin-x86_64
chmod +x ~/colima
~/colima version
check that it is indeed version 0.6.6
~/colima delete
~/colima prune -a
~/colima start --vm-type vz --mount-type virtiofs ….  # add all necessary parameters.
~/colima stop
rm ~/colima
brew install colima
colima start
colima version
```

**Comment by abiosoft** [comment] 2023-12-13 17:55
This specifically happens with vz on intel devices, right?

**Comment by AndreasA** [comment] 2023-12-14 07:53
@abiosoft I also just tried the following lima config and manually creating it, and it fails as well:

```yaml
images:
  - location: 'https://github.com/abiosoft/colima-core/releases/download/v0.6.7/ubuntu-23.10-minimal-cloudimg-amd64.qcow2'
    arch: 'x86_64'
    digest: 'sha512:9980ac00edc0a0b75e9c924f25f3403e76ef8fd680ee1847082de543a8ff851413992a18b065c53092edf298d11de50b0b129ece1ec17217bd8a6e9266b22345'
vmType: 'vz'
mountType: 'virtiofs'
```

maybe the image or the conversion from qcow2 to raw has some issue. I think the previous one was raw format?

I also found that lima issue, might be related ? https://github.com/lima-vm/lima/issues/1964

though the file does not seem to be empty that has been created but...

**Comment by AndreasA** [comment] 2023-12-14 08:06
@abiosoft I did one more test and the following did indeed work (using limactl manually):

download and convert image manually to raw using qemu-img 

```sh
curl -o ubuntu-23.10-minimal-cloudimg-amd64.qcow2 -L https://github.com/abiosoft/colima-core/releases/download/v0.6.7/ubuntu-23.10-minimal-cloudimg-amd64.qcow2
qemu-img convert ubuntu-23.10-minimal-cloudimg-amd64.qcow2 ubuntu-23.10-minimal-cloudimg-amd64.raw
```

and then using the following lime config I was able to successfully create the instance:

```yaml
images:
  - location: './ubuntu-23.10-minimal-cloudimg-amd64.raw'
    arch: 'x86_64'
vmType: 'vz'
mountType: 'virtiofs'
```

so I guess the issue is indeed lima qcow2 auto-conversion to raw image.

**Comment by abiosoft** [comment] 2023-12-14 08:07
Interesting. 

Thanks for the detailed feedback.

**Comment by mvmn** [comment] 2023-12-21 15:52
Got the same issue

**Comment by AndreasA** [comment] 2023-12-22 06:31
@abiosoft The easiest solution would be to switch back to the raw image type until the lima bug is fixed.
at least for intel macs.

**Comment by abiosoft** [comment] 2023-12-22 07:03
@AndreasA colima can actually do the conversion to raw as a temporary workaround.

This is specific to Intel as I am unable to reproduce on my m1 devices.

**Comment by AndreasA** [comment] 2023-12-22 07:30
@abiosoft that would be even better. strictly speaking it could always be done for now for VZ vm type, as lima does the conversion anyway.

**Comment by AndreasA** [comment] 2024-01-10 07:40
@abiosoft any news when this might be fixed? as it bascially prevents me to do a colima delete (though it is probably not necessary now that I have it running again with 0.6.7) without having to downgrade again.

**Comment by simonjharris** [comment] 2024-02-03 11:16
I am seeing the same error on an M2 air with 0.6.8. Is there any workaround for this?

**Comment by simonjharris** [comment] 2024-02-05 17:09
I downgraded to 0.5.6 and it's working fine on there. M3 is using vz by default AFAIK so likely same issue @pgarrett-twc.

**Comment by terev** [comment] 2024-02-07 10:09
If there were a raw version of the latest colima image, users could workaround this with an override right?

**Comment by ralph089** [comment] 2024-02-09 10:51
Nothing from the above solutions worked for me (M2 Mac).

**Comment by wondris009** [comment] 2024-02-12 09:14
Stopped working on M1 as well. During this phase:
**> 3.50 GiB / 3.50 GiB (100.00%) 393.94 MiB/stime="2024-02-12T10:07:40+01:00" level=info msg="Expanding to 100GiB"**

It eats all my HDD space. My settings is:

```# Number of CPUs to be allocated to the virtual machine.
# Default: 2
cpu: 4
 
# Size of the disk in GiB to be allocated to the virtual machine.
# NOTE: changing this has no effect after the virtual machine has been created.
# Default: 60
disk: 100
 
# Size of the memory in GiB to be allocated to the virtual machine.
# Default: 2
memory: 8
 
# Architecture of the virtual machine (x86_64, aarch64, host).
# Default: host
arch: aarch64
 
# Container runtime to be used (docker, containerd).
# Default: docker
runtime: docker

...
 
# Virtual Machine type (qemu, vz)
# NOTE: this is macOS 13 only. For Linux and macOS <13.0, qemu is always used.
#
# vz is macOS virtualization framework and requires macOS 13
#
# Default: qemu
vmType: vz

# Utilise rosetta for amd64 emulation (requires m1 mac and vmType `vz`)
# Default: false
rosetta: true
 
# Volume mount driver for the virtual machine (virtiofs, 9p, sshfs).
#
# virtiofs is limited to macOS and vmType `vz`. It is the fastest of the options.
#
# 9p is the recommended and the most stable option for vmType `qemu`.
#
# sshfs is faster than 9p but the least reliable of the options (when there are lots
# of concurrent reads or writes).
#
# Default: virtiofs (for vz), sshfs (for qemu)
mountType: virtiofs```

**Comment by egze** [comment] 2024-02-12 12:53
Works on M1 Pro, but doesn't work on M3 for me

**Comment by wondris009** [comment] 2024-02-12 15:08
I changed the space back to default (60GB, i had about 70GB when i was trying 100GB option) then the expanding finished without problem (maybe it would finish with 100GB as well if i had that space left). I was just wondering why it stopped working when i didn't make any change. But now after some docker and colima reinstalation its working again. My use case was that my ARM64 Oracle DB stopped working.

**Comment by pgarrett-twc** [comment] 2024-02-13 03:31
> What fixed my issues was
> `brew uninstall colima lima qemu`
> `rm -rf ~/.colima ~/.lima`
> restarted macOS
> 'brew install --HEAD colima'

This worked for me on an M3 with 14.3.1 (23D60).

**Comment by simonjharris** [comment] 2024-02-13 08:50
> > What fixed my issues was
> > `brew uninstall colima lima qemu`
> > `rm -rf ~/.colima ~/.lima`
> > restarted macOS
> > 'brew install --HEAD colima'
> 
> This worked for me on an M3 with 14.3.1 (23D60).

This actually did work for me, but it still took around 5 minutes to expand the disk. So now I'm wondering if I just wasn't patient enough before 😆 

On 0.5.x, initial startup is much faster.

**Comment by egze** [comment] 2024-02-13 09:22
Updated my iMac to 14.3.1 from 14.2.1 and it worked with `brew install --HEAD colima` 🤯

**Comment by rfay** [comment] 2024-02-13 23:01
When having this problem I also see caching behavior:
`Using cache "/Users/rfay/Library/Caches/lima/download/by-url-sha256/63f6e459cc61986ae586c5402c4e6e95ddc9073986f2a766ff662f19e0151407/data"`

So best to `rm -rf ~/Library/Caches/lima` as well.

**Comment by literatesnow** [comment] 2024-02-16 21:16
I also have this problem on a M2 Max, Sonoma 14.3.1, colima 0.6.8.

```
colima start --arch aarch64 --cpu 4 --disk 128 --memory 6 --vm-type=vz --vz-rosetta
```

Took 1 hour 20 minutes, activity monitor shows around 15MB/sec disk writes.

Using `limactl start ...` (from [above](https://github.com/abiosoft/colima/issues/930#issuecomment-1935704596)) created the VM in under a minute.

**Comment by mastertheif** [comment] 2024-02-20 08:49
Same issue here on an older intel MacOS Ventura 13.6.4, with colima 0.6.7, if i recall correctly the version 0.6.6 had the same issue.
I was able to circumvent the issue by downgrading to colima 0.6.5, start the vm, stop it and then upgrade

Here is how if it helps someone
```bash
brew uninstall colima && rm -rf ~/.colima # Removing the folder just in case it don´t thins it is necessary

# this is the formulae for the version 0.6.5
curl https://raw.githubusercontent.com/Homebrew/homebrew-core/c3c2a6daa274d5f4b9cc7bb3d25b3cfde50b4e0a/Formula/c/colima.rb -o /tmp/colima.rb 

brew install --formulae /tmp/colima.rb
colima start --vm-type=vz --mount-type=virtiofs --disk 60
colima stop

brew update && brew upgrade
```

**Comment by igarridot** [comment] 2024-02-21 20:17
Same issue on Apple Silicon M2 running MacOS Sonoma 14.3.1 and Colima 0.6.8 but working fine in 0.6.5.

**Comment by rfay** [comment] 2024-02-22 21:08
I also found that I was able to get past this by using `--disk 60` instead of `--disk 100`. I have plenty of disk. I have no idea why that would be an issue.

I also noted that during several failures I saw that there were zombie instances of limactl that could not be killed, so when I saw them (`ps -ef |grep lima`) I had to restart to get rid of them.

**Comment by pborobov** [comment] 2024-03-09 16:57
> The only solution I found was to temporarily downgrade to 0.6.6, do the start there, then reinstall 0.6.7.
> 
> So something like this - probably not all deletions etc. are necessary but to be safe I did them multiple times:
> 
> ```
> colima stop -f
> # Reboot macOS - warning most likely macOS will freeze during reboot and require a force shutdown.
> colima delete
> colima prune -a
> rm -rf ~/.lima
> rm -rf ~/.colima
> rm -rf ~/Library/Caches/colima
> rm -rf ~/Library/Caches/lima
> brew uninstall colima
> curl -o ~/colima -L https://github.com/abiosoft/colima/releases/download/v0.6.6/colima-Darwin-x86_64
> chmod +x ~/colima
> ~/colima version
> check that it is indeed version 0.6.6
> ~/colima delete
> ~/colima prune -a
> ~/colima start --vm-type vz --mount-type virtiofs ….  # add all necessary parameters.
> ~/colima stop
> rm ~/colima
> brew install colima
> colima start
> colima version
> ```

Facing the same issue, going through 0.6.6 initialization and then upgrading to latest did the job well.

**Comment by blvp** [comment] 2024-03-09 16:58
> The only solution I found was to temporarily downgrade to 0.6.6, do the start there, then reinstall 0.6.7.
> 
> So something like this - probably not all deletions etc. are necessary but to be safe I did them multiple times:
> 
> ```
> colima stop -f
> # Reboot macOS - warning most likely macOS will freeze during reboot and require a force shutdown.
> colima delete
> colima prune -a
> rm -rf ~/.lima
> rm -rf ~/.colima
> rm -rf ~/Library/Caches/colima
> rm -rf ~/Library/Caches/lima
> brew uninstall colima
> curl -o ~/colima -L https://github.com/abiosoft/colima/releases/download/v0.6.6/colima-Darwin-x86_64
> chmod +x ~/colima
> ~/colima version
> check that it is indeed version 0.6.6
> ~/colima delete
> ~/colima prune -a
> ~/colima start --vm-type vz --mount-type virtiofs ….  # add all necessary parameters.
> ~/colima stop
> rm ~/colima
> brew install colima
> colima start
> colima version
> ```

Facing the same issue, going through 0.6.6 initialization and then upgrading to latest did the job well.

**Comment by rsau** [comment] 2024-03-11 21:39
I experimented with different disk sizes on M1, Sonoma 14.4. 

If disk is 40 then it starts very quickly without any issues but for other sizes it gets stuck

colima 0.6.8

For last 10 mins
 `> 3.50 GiB / 3.50 GiB (100.00%) 413.59 MiB/stime="2024-03-12T08:27:54+11:00" level=info msg="Expanding to 160GiB"` 



I have 273 GB free

**Comment by sgtsquiggs** [comment] 2024-03-12 20:19
Using `brew install --HEAD colima` worked for me on a fresh M3

**Comment by Flexicon** [comment] 2024-03-14 09:17
Can confirm that using `brew install --HEAD colima` worked for a few people in my organization.

It seems to specifically be people that are on M2/3 that are affected. Intel and M1 seems fine for the most part.

**Comment by krystof-k** [comment] 2024-03-27 07:12
Mac mini M1, this

```shell
colima start --cpu 8 --memory 12 --disk 128 --arch aarch64 --vm-type=vz --vz-rosetta
```

took several hours writing 15 MB/s to the disk.

**Comment by AndreasA** [comment] 2024-05-08 05:10
I haven't tried this yet but the newest lima 0.22.0 version should include a bugfix regarding the issue https://github.com/lima-vm/lima/issues/1964 so I hope this is fixed now as well. Bugfix:  https://github.com/lima-vm/lima/pull/2255 which is mentioned in the full changes: https://github.com/lima-vm/lima/milestone/45?closed=1

**Comment by abiosoft** [comment] 2024-05-08 05:23
This has been fixed in the latest head. `brew install --head colima`.

It seems the issue is due to the way the Colima disk image was compressed. With compression disabled, it works as desired. The only downside is heavier download during first startup.

**Comment by Flexicon** [comment] 2024-05-08 14:57
@abiosoft any timeline on when the change will be released and we can just install latest (`v0.6.9`)?

**Comment by luisdavim** [comment] 2024-05-16 19:58
I had the same issue and using `brew install --head colima` fixed it, any chances of a new release soon?

**Comment by abiosoft** [comment] 2024-05-17 17:49
> I had the same issue and using brew install --head colima fixed it, any chances of a new release soon?

Yeah, over the weekend.

**Comment by abiosoft** [comment] 2024-05-18 05:55
[v0.6.9](https://github.com/abiosoft/colima/releases/tag/v0.6.9) has been released and should be available on homebrew shortly.

**Comment by literatesnow** [comment] 2024-06-28 03:29
> I also have this problem on a M2 Max, Sonoma 14.3.1, colima 0.6.8.

Version 0.6.9 confirmed to have fixed the issue for me, thanks!

**Comment by abiosoft** [comment] 2024-07-29 19:24
Colima now does this instead https://github.com/abiosoft/colima/issues/930#issuecomment-1855365096 as a permanent fix and would be part of the imminent next release.

The disk image downloads are smaller again but without the disk expansion issues.

Anyone can try the development version with `brew install --head colima`.

**Closed by abiosoft** 2024-07-29 19:24 UTC
