### ISSUE TITLE
dns stops working after a while

### ISSUE THREAD

**Issue by brennan-airtime** [abiosoft/colima#779] opened 2023-08-16 17:19 UTC
### Description

dns seems to have issues after running the VM for an amount of time. Maybe something to do with suspend/resume Recreating the VM restores DNS:

```
colima delete ; colima start --cpu 6 --memory 24 --disk 800 --vm-type=vz
```

github.com fails during docker build, inside containers and even if I ssh into the VM.

DNS works fine on my host.

### Version

colima version 0.5.5
git commit: 6251dc2

runtime: docker
arch: x86_64
client: v24.0.2
server: v23.0.6

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [X] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [ ] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using macOS Virtualization.Framework
INFO[0000] arch: x86_64
INFO[0000] runtime: docker
INFO[0000] mountType: virtiofs
INFO[0000] socket: unix:///Users/brennan/.colima/default/docker.sock

### Reproduction Steps

1. `colima start --cpu 6 --memory 24 --disk 800 --vm-type=vz`
2. use it for a while
3. dns becomes very intermittent

**Comment by luisdavim** [comment] 2023-08-18 00:00
I have the same issue but it only seems to happen wen using `--vm-type=vz`

**Comment by brennan-airtime** [comment] 2023-08-21 17:17
If I do a dns query with nslookup or dig from inside and set say cloudflare 1.1.1.1 it works fine. I believe there is a DNS proxy or some DNS component inside the colima VM having issues.

**Comment by michaeldiscala** [comment] 2023-08-21 23:59
My team is seeing this same issue periodically, using the `vz` vm type. My network config is as follows:

```
# Network configurations for the virtual machine.
network:
  # Assign reachable IP address to the virtual machine.
  # NOTE: this is currently macOS only and ignored on Linux.
  # Default: false
  address: true
  
  # Custom DNS resolvers for the virtual machine.
  #
  # EXAMPLE
  # dns: [8.8.8.8, 1.1.1.1]
  #
  # Default: []
  dns:
    - 8.8.8.8
    - 1.1.1.1
  
  # DNS hostnames to resolve to custom targets using the internal resolver.
  # This setting has no effect if a custom DNS resolver list is supplied above.
  # It does not configure the /etc/hosts files of any machine or container.
  # The value can be an IP address or another host.
  #
  # EXAMPLE
  # dnsHosts:
  #   example.com: 1.2.3.4
  dnsHosts: {}
  
  # Network driver to use (slirp, gvproxy), (requires vmType `qemu`)
  #   - slirp is the default user mode networking provided by Qemu
  #   - gvproxy is an alternative to VPNKit based on gVisor https://github.com/containers/gvisor-tap-vsock
  # Default: gvproxy
  driver: gvproxy
```


Please let me know if there's any diagnostic information that would be helpful for me to share. Thank you!

**Comment by brennan-airtime** [comment] 2023-08-30 17:10
It seems it is the docker daemon dns proxy having the issue. Next time it happens I'll just try restarting `dockerd` to see if it resolves the issue.

**Comment by rawroland** [comment] 2023-10-20 13:18
I am also experiencing this issue, and would like to add the reasons which cause the problem, if this could be helpful. It happens to me both after my system goes to sleep and when I switched my network connection, that is from lan to wifi and vice versa. The only thing that helps for me is if I restart colima.

**Comment by rfay** [comment] 2023-11-01 17:45
I imagine this might be a duplicate of 
* https://github.com/abiosoft/colima/issues/466

**Closed** 2023-11-12 10:34 UTC
