### ISSUE TITLE
timeout when building from public.ecr.aws

### ISSUE THREAD

**Issue by kigawas** [abiosoft/colima#164] opened 2022-02-03 03:31 UTC
## Environment
```
$ colima version
colima version HEAD-6f7f8a9
git commit: 6f7f8a9662984b23a110473095929f1ef3a671d8

runtime: containerd
arch: x86_64
client: v0.16.0
server: v1.5.8
```

## Error log

```
[+] Building 30.1s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                           0.0s
 => => transferring dockerfile: 538B                                                                                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                                                                              0.1s
 => => transferring context: 2B                                                                                                                                                                                0.1s
 => ERROR [internal] load metadata for public.ecr.aws/lambda/python:3.9                                                                                                                                       30.0s
------
 > [internal] load metadata for public.ecr.aws/lambda/python:3.9:
------
Dockerfile:1
--------------------
   1 | >>> FROM public.ecr.aws/lambda/python:3.9
   2 |
   3 |     COPY pyproject.toml poetry.lock ./
--------------------
error: failed to solve: public.ecr.aws/lambda/python:3.9: failed to do request: Head "https://public.ecr.aws/v2/lambda/python/manifests/3.9": dial tcp 75.2.101.78:443: i/o timeout
FATA[0030] unrecognized image format
```

However it's okay to pull:
```
public.ecr.aws/lambda/python:3.9:                                                 resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:8dc4d4145c1a05ed727b2e57e611c302c7f7188b406ba0934a612166458e524e:    exists         |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:b0639a2506b96463f50816085ad990b9bc9794ca24090f39dfb3241e4d109eee: done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:d424101ad44cc10fbc87bf49ad3f5b1cdb34a2e52ec052ab67a16ec72b6677a2:   done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 1.2 s                                                                    total:   0.0 B (0.0 B/s)
```

**Comment by abiosoft** [comment] 2022-02-10 06:51
@kigawas does this still fail after multiple retries and even after the image is pulled?

**Comment by abiosoft** [comment] 2022-02-10 06:55
and kindly verify if it is not yet fixed with [this pre-release](https://github.com/abiosoft/colima/releases/tag/v0.3.3-pre-02)

**Comment by abiosoft** [comment] 2022-02-10 13:37
@kigawas is this a public image `public.ecr.aws/lambda/python:3.9`? Can I try it on my end?

**Comment by kigawas** [comment] 2022-02-11 08:52
> @kigawas is this a public image `public.ecr.aws/lambda/python:3.9`? Can I try it on my end?

You should have no problem pulling it. But it just fails when building

**Comment by abiosoft** [comment] 2022-02-15 06:02
> > @kigawas is this a public image `public.ecr.aws/lambda/python:3.9`? Can I try it on my end?
> 
> You should have no problem pulling it. But it just fails when building

@kigawas can you share the Dockerfile?

**Comment by kigawas** [comment] 2022-02-15 08:35
@abiosoft 

You can just use the simplest one:

```dockerfile
FROM public.ecr.aws/lambda/python:3.9
CMD ["echo", "test"]
```

Then 
```bash
$ colima nerdctl build .
[+] Building 30.1s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                           0.0s
 => => transferring dockerfile: 96B                                                                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                                                                0.0s
 => ERROR [internal] load metadata for public.ecr.aws/lambda/python:3.9                                                                                                                                       30.0s
------
 > [internal] load metadata for public.ecr.aws/lambda/python:3.9:
------
Dockerfile:1
--------------------
   1 | >>> FROM public.ecr.aws/lambda/python:3.9
   2 |     CMD ["echo", "test"]
   3 |
--------------------
error: failed to solve: public.ecr.aws/lambda/python:3.9: failed to do request: Head "https://public.ecr.aws/v2/lambda/python/manifests/3.9": dial tcp 99.83.145.10:443: i/o timeout
FATA[0030] unrecognized image format
FATA[0030] exit status 1
```

**Comment by abiosoft** [comment] 2022-02-15 08:46
I am still unable to reproduce this.

Is it same behaviour if you use custom dns e.g. `colima start --dns 8.8.8.8 --dns 8.8.4.4`.
P.S: use the [pre-release](https://github.com/abiosoft/colima/releases/tag/v0.3.3-pre-02).

**Comment by kigawas** [comment] 2022-02-15 09:03
> --dns 8.8.8.8 --dns 8.8.4.4

Are you using containerd runtime? I deleted and started by `./colima start --runtime containerd --dns 8.8.8.8 --dns 8.8.4.4`, but the `./colima nerdctl build .` command didn't work.

**Comment by abiosoft** [comment] 2022-02-15 09:06
> Are you using containerd runtime? 

yeah, I have tested successfully with both docker and containerd runtimes.

> I deleted and started by `./colima start --runtime containerd --dns 8.8.8.8 --dns 8.8.4.4`, but the `./colima nerdctl build .` command didn't work.

do you still get same error?

**Comment by kigawas** [comment] 2022-02-15 09:26
Oh I see, it looks like the problem is that direct tcp connection is prohibited.

It's probably because that the head request is not sent as a standard HTTPS request so the proxy setting is not effective.

**Comment by abiosoft** [comment] 2022-02-15 09:32
are you using a proxy?

**Comment by kigawas** [comment] 2022-02-21 06:55
> are you using a proxy?

Yes

**Comment by kigawas** [comment] 2022-02-21 07:59
OK, looks like `limactl` and `lima nerdctl` works as expected. Can you update the dependency? @abiosoft

**Closed** 2022-02-28 15:01 UTC
