### ISSUE TITLE
Failing to Start Colima because of problems with base image download or verify

### ISSUE THREAD

**Issue by KudesnikOk** [abiosoft/colima#1092] opened 2024-08-03 11:18 UTC
### Description

After fresh install of Colima via home-brew and starting it with Colima start I'm getting following errors in log:
 ```
/ % colima start --very-verbose
TRAC[0000] cmd ["limactl" "info"]                       
TRAC[0000] cmd ["limactl" "list" "colima" "--json"]     
TRAC[0000] error retrieving running instance: instance 'colima' does not exist 
INFO[0000] starting colima                              
INFO[0000] runtime: docker                              
TRAC[0000] cmd ["/opt/homebrew/bin/colima" "daemon" "status" "default"] 
TRAC[0000] cmd ["/opt/homebrew/bin/colima" "daemon" "start" "default" "--inotify" "--inotify-runtime" "docker" "--inotify-dir" "/Users/***/" "--inotify-dir" "/tmp/colima/" "--very-verbose"] 
TRAC[0000] cmd ["/opt/homebrew/bin/colima" "daemon" "status" "default"] 
TRAC[0001] cmd ["/opt/homebrew/bin/colima" "daemon" "status" "default"] 
INFO[0001] creating and starting ...                     context=vm
INFO[0001] downloading disk image ...                    context=vm
TRAC[0001] cmd ["mkdir" "-p" "/Users/***/Library/Caches/colima/caches"] 
TRAC[0001] cmd ["curl" "-Ls" "-o" "/dev/null" "-w" "%{url_effective}" "https://github.com/abiosoft/colima-core/releases/download/v0.7.0-3/ubuntu-24.04-minimal-cloudimg-arm64-docker.qcow2"] 
TRAC[0676] cmd int ["curl" "-L" "-#" "-C" "-" "-o" "/Users/***/Library/Caches/colima/caches/4e1d6f9076c36aa5dc942101c931e0230f3c2c4eafae3c050ebc072dda0ad76b.downloading" "https://objects.githubusercontent.com/github-production-release-asset-2e65be/716288883/43841e31-7d6a-4dd1-a604-1d19596bff57?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240803%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240803T090328Z&X-Amz-Expires=300&X-Amz-Signature=ef99865bc49e4a09c160d9b0e22ed45618c0d9633c33e2ecea887bb832ed19fd&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=716288883&response-content-disposition=attachment%3B%20filename%3Dubuntu-24.04-minimal-cloudimg-arm64-docker.qcow2&response-content-type=application%2Foctet-stream"] 
TRAC[0677] cmd ["sh" "-c" "cd /Users/***/Library/Caches/colima/caches/ && echo \"4c6f3b90067629ebe9bad3c156d6f849ccfb54585ec1af0ee72a9f58c20b9794504a6742e74c9259056db951f9f6d9168a303ea819219278a54f4df4c66a3cf6  4e1d6f9076c36aa5dc942101c931e0230f3c2c4eafae3c050ebc072dda0ad76b.downloading\" | shasum -a 512 --check --status"] 
TRAC[0677] cmd ["mv" "/Users/***/Library/Caches/colima/caches/4e1d6f9076c36aa5dc942101c931e0230f3c2c4eafae3c050ebc072dda0ad76b.downloading" "/Users/***/Library/Caches/colima/caches/4e1d6f9076c36aa5dc942101c931e0230f3c2c4eafae3c050ebc072dda0ad76b.downloading.invalid"] 
FATA[0677] error starting vm: error at 'creating and starting': error getting qcow image: error during image download: error downloading 'https://github.com/abiosoft/colima-core/releases/download/v0.7.0-3/ubuntu-24.04-minimal-cloudimg-arm64-docker.qcow2': error validating SHA sum for 'ubuntu-24.04-minimal-cloudimg-arm64-docker.qcow2': exit status 1
```

This is with --head version of colima. With general version I'm just getting error while image download. Image download seems to be very slow. Still, I'm able to download image directly from GitHub.
As I see, file 4e1d6f9076c36aa5dc942101c931e0230f3c2c4eafae3c050ebc072dda0ad76b.downloading.invalid is empty, as if call to https://objects.githubusercontent.com/ doesn't get me anything.

Anything I can do to overcome this?

### Version

colima version HEAD-4d8304b
git commit: 4d8304baf7f871d0f313524b6be4fc3e9ce2a5ec
limactl version 0.22.0
qemu-img version 9.0.2

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

FATA[0000] colima is not running

### Reproduction Steps

1. brew install colima
2. colima start

### Expected behaviour

colima starts

**Comment by abiosoft** [comment] 2024-08-03 12:49
Duplicate of #995.

**Closed by abiosoft** 2024-08-03 12:49 UTC
