### ISSUE TITLE
Running Docker containers on colima on Mac M1 is very very slow

### ISSUE THREAD

**Issue by cosygarcia** [abiosoft/colima#204] opened 2022-03-02 14:45 UTC
Each command launched inside containers are very very slow.

I have 16GB of RAM and have launched Colima as follows :
colima start --cpu 4 --memory 6 --disk 10 --arch aarch64

Any idea to improve perf ?

**Comment by rfay** [comment] 2022-03-02 14:50
I find colima quite fast on mac M1 (using arm64 images), probably faster than docker can, but I haven't done benchmarks.  Make sure you're using arm64 images.

**Comment by cosygarcia** [comment] 2022-03-03 08:31
> @cosygarcia this sounds like it is running in emulation mode? Can you kindly ensure you have the right version of qemu?
> 
> What is the output of `qemu-img --version` ?

I am running version 6.2 :

qemu-img --version
qemu-img version 6.2.0
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers

**Comment by cosygarcia** [comment] 2022-03-03 08:32
> I find colima quite fast on mac M1 (using arm64 images), probably faster than docker can, but I haven't done benchmarks. Make sure you're using arm64 images.

When you say "arm64 images" do you speak about container images ?

**Comment by rfay** [comment] 2022-03-03 15:19
@cosygarcia docker images, like computers, can come in various architectures. The most common are amd64 (Intel) and arm64 (arm). Your computer is an arm64 machine; the M1 and the raspberry pi are two of the most important mass-market arm64 machines, before that it was pretty obscure. But when you try to run an amd64 image (as a container) on an arm64 machine, a lot of work has to be done to translate between the two architectures, and it makes things really slow. 

Not every docker image has both, many do not. If you look at Ubuntu, for example, you'll see that the more recent images all have several architectures, including arm64 and amd64. `docker pull` or `docker run` will "do the right thing" with these and choose the native architecture.  But there are many, many docker images up on hub.docker.com that are built only for amd64 and they're very painfully slow (and unreliable) to run across architectures.

**Comment by pedantic79** [comment] 2022-03-09 03:45
While amd64 images work with colima, the performance is quite poor. I assume that is because qemu inside the colima VM is doing emulation instead of using rosetta.

Here is the 7zip benchmark using rosetta versus inside a container:

```
dnn@Daniels-MBP ~ » file ./7z
./7z: Mach-O 64-bit executable x86_64
dnn@Daniels-MBP ~ » ./7z b -mmt2

7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,10 CPUs x64)

x64
CPU Freq:  2468  2943  3187  3197  3190  3201  3206  3185  3195

RAM size:   32768 MB,  # CPU hardware threads:  10
RAM usage:    441 MB,  # Benchmark threads:      2

                       Compressing  |                  Decompressing
Dict     Speed Usage    R/U Rating  |      Speed Usage    R/U Rating
         KiB/s     %   MIPS   MIPS  |      KiB/s     %   MIPS   MIPS

22:      11592   161   6989  11277  |     103431   200   4416   8831
23:      11451   173   6733  11668  |     102256   200   4427   8851
24:      11214   182   6643  12057  |     100583   200   4417   8830
25:      11169   186   6840  12753  |      98372   200   4379   8756
----------------------------------  | ------------------------------
Avr:             176   6801  11939  |              200   4410   8817
Tot:             188   5606  10378
```

amd64 Container
```
dnn@Daniels-MBP ~ » docker run --platform=linux/amd64 --rm -it backplane/7z:latest b
Unable to find image 'backplane/7z:latest' locally
latest: Pulling from backplane/7z
41dcc117e123: Pull complete
1fddf70b5c63: Pull complete
740a24447a36: Pull complete
Digest: sha256:f442b7c36e6babea84e76ee73de428939979895c50ae8543b2788a2539d1b47b
Status: Downloaded newer image for backplane/7z:latest

7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=C.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs QEMU TCG CPU version 2.5+ (60FB1),ASM,AES-NI)

QEMU TCG CPU version 2.5+ (60FB1)
CPU Freq: 2285714 21333333 - - - - 512000000 512000000 512000000

RAM size:    1980 MB,  # CPU hardware threads:   2
RAM usage:    441 MB,  # Benchmark threads:      2

                       Compressing  |                  Decompressing
Dict     Speed Usage    R/U Rating  |      Speed Usage    R/U Rating
         KiB/s     %   MIPS   MIPS  |      KiB/s     %   MIPS   MIPS

22:       2176   141   1502   2117  |      35044   199   1507   2992
23:       2226   149   1526   2269  |      34947   200   1515   3025
24:       2212   154   1542   2379  |      34277   200   1507   3009
25:       2128   159   1528   2431  |      33180   199   1481   2953
----------------------------------  | ------------------------------
Avr:             151   1524   2299  |              199   1502   2995
Tot:             175   1513   2647
```

For comparison with arm64 macos (installed via homebrew):
```
Avr:             172   8406  14431  |              200   4839   9665
```

Versus container (same container, as it is available in both arm64 and amd64):
```
Avr:             183   8395  15393  |              199   4850   9672
```

**Comment by K-Stefan** [comment] 2022-03-30 07:10
I can confirm the challenges of the Issue. 

I used Colima with my Intel MacBook Pro (15" 2018) quite well. I switched now to a new MacBook Pro (16" 2021) with the Apple M1 Pro Silicon.
One of my main development work is to write AWS CDK Apps. The local build/synth process uses docker container.

Unfortunately, the performance dropped dramatically with the new M1 MacBook. Previous build/synth builds were less than a minute. Now greater 1 hour. 

Colima is started with the args:

```bash
colima start --memory 8 -cpu 8
```

Two points make me suspicious regarding the slow performance.

1. `qemu-system-aarch64` is running as type Intel in the MacOS' activity monitor - is this normal behavior?

2. M1 Hardware Acceleration HVF is not used - as shown in `ps` it is set to `accel=tcg` - not sure if this is only necessary or provide performance acceleration on running aarch64 images on M1

```bash
ps | grep qemu
17143 ttys000   6:58.01 /usr/local/bin/qemu-system-aarch64 -cpu cortex-a72 -machine virt,accel=tcg,highmem=off -smp 8,sockets=1,cores=8,threads=1 -m 8192 -drive if=pflash,format=raw,readonly=on,file=/usr/local/share/qemu/edk2-aarch64-code.fd -boot order=d,splash-time=0,menu=on -drive file=/Users/my.user/.lima/colima/basedisk,media=cdrom,readonly=on -drive file=/Users/my.user/.lima/colima/diffdisk,if=virtio -cdrom /Users/my.user/.lima/colima/cidata.iso -netdev user,id=net0,net=192.168.5.0/24,dhcpstart=192.168.5.15,hostfwd=tcp:127.0.0.1:49976-:22 -device virtio-net-pci,netdev=net0,mac=52:55:55:e2:6d:34 -netdev vde,id=net1,sock=/Users/my.user/.colima/network/vmnet.ptp -device virtio-net-pci,netdev=net1,mac=52:55:55:bc:18:8e -device virtio-rng-pci -display none -vga none -device ramfb -device qemu-xhci,id=usb-bus -device usb-kbd,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -parallel none -chardev socket,id=char-serial,path=/Users/my.user/.lima/colima/serial.sock,server=on,wait=off,logfile=/Users/my.user/.lima/colima/serial.log -serial chardev:char-serial -chardev socket,id=char-qmp,path=/Users/my.user/.lima/colima/qmp.sock,server=on,wait=off -qmp chardev:char-qmp -name lima-colima -pidfile /Users/my.user/.lima/colima/qemu.pid
```

## Setup & Versions

I installed `colima` with brew.After the the poor performance I upgrade the HEAD for colima & lima but without any noticable change.

## colima

- colima v0.3.4
- colima version HEAD-37a6de0

### lima

- lima 0.9.2
- limactl version HEAD-e021ce7

### QEMU

```
qemu-system-aarch64 -version
QEMU emulator version 6.2.0
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
```

### macOS

12.3

## Other Issues

I'm also experience the same issues as described in https://github.com/abiosoft/colima/issues/175 - the `colima start` process takes minutes (>5 min)

**Comment by K-Stefan** [comment] 2022-03-30 14:36
> I can confirm the challenges of the Issue.
> 
> I used Colima with my Intel MacBook Pro (15" 2018) quite well. I switched now to a new MacBook Pro (16" 2021) with the Apple M1 Pro Silicon. One of my main development work is to write AWS CDK Apps. The local build/synth process uses docker container.
> 
> Unfortunately, the performance dropped dramatically with the new M1 MacBook. Previous build/synth builds were less than a minute. Now greater 1 hour.
> 
> Colima is started with the args:
> 
> ```shell
> colima start --memory 8 -cpu 8
> ```
> 
> Two points make me suspicious regarding the slow performance.
> 
> 1. `qemu-system-aarch64` is running as type Intel in the MacOS' activity monitor - is this normal behavior?
> 2. M1 Hardware Acceleration HVF is not used - as shown in `ps` it is set to `accel=tcg` - not sure if this is only necessary or provide performance acceleration on running aarch64 images on M1
> 
> ```shell
> ps | grep qemu
> 17143 ttys000   6:58.01 /usr/local/bin/qemu-system-aarch64 -cpu cortex-a72 -machine virt,accel=tcg,highmem=off -smp 8,sockets=1,cores=8,threads=1 -m 8192 -drive if=pflash,format=raw,readonly=on,file=/usr/local/share/qemu/edk2-aarch64-code.fd -boot order=d,splash-time=0,menu=on -drive file=/Users/my.user/.lima/colima/basedisk,media=cdrom,readonly=on -drive file=/Users/my.user/.lima/colima/diffdisk,if=virtio -cdrom /Users/my.user/.lima/colima/cidata.iso -netdev user,id=net0,net=192.168.5.0/24,dhcpstart=192.168.5.15,hostfwd=tcp:127.0.0.1:49976-:22 -device virtio-net-pci,netdev=net0,mac=52:55:55:e2:6d:34 -netdev vde,id=net1,sock=/Users/my.user/.colima/network/vmnet.ptp -device virtio-net-pci,netdev=net1,mac=52:55:55:bc:18:8e -device virtio-rng-pci -display none -vga none -device ramfb -device qemu-xhci,id=usb-bus -device usb-kbd,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -parallel none -chardev socket,id=char-serial,path=/Users/my.user/.lima/colima/serial.sock,server=on,wait=off,logfile=/Users/my.user/.lima/colima/serial.log -serial chardev:char-serial -chardev socket,id=char-qmp,path=/Users/my.user/.lima/colima/qmp.sock,server=on,wait=off -qmp chardev:char-qmp -name lima-colima -pidfile /Users/my.user/.lima/colima/qemu.pid
> ```
> 
> ## Setup & Versions
> I installed `colima` with brew.After the the poor performance I upgrade the HEAD for colima & lima but without any noticable change.
> 
> ## colima
> * colima v0.3.4
> * colima version HEAD-37a6de0
> 
> ### lima
> * lima 0.9.2
> * limactl version HEAD-e021ce7
> 
> ### QEMU
> ```
> qemu-system-aarch64 -version
> QEMU emulator version 6.2.0
> Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
> ```
> 
> ### macOS
> 12.3
> 
> ## Other Issues
> I'm also experience the same issues as described in #175 - the `colima start` process takes minutes (>5 min)

I found the issue. The problem I trusted the software package of our internal MDM store. iTerm was outdated and it ran in Intel Mode, therefore, Homebrew installed qemu as an intel variant. 

After re-install with Colima with `/opt/homebrew/bin/brew`. It now runs as excepted. Qemu is shown as type Apple in macOS' activity monitoring. Also `accel=hvf` is enabled.

```
ps | grep qemu
26572 ttys001    0:04.55 /opt/homebrew/bin/qemu-system-aarch64 -cpu host -machine virt,accel=hvf,highmem=off 
```

**Comment by abiosoft** [comment] 2022-03-30 16:19
@cosygarcia this https://github.com/abiosoft/colima/issues/204#issuecomment-1083220386 is probably your situation. Your qemu version may be intel version utilising rosetta.

**Comment by pedantic79** [comment] 2022-03-30 16:32
@abiosoft Is the follow correct? 

For an M1 Mac, the fastest configuration would be to run the arm64 version of qemu-system-aarch64 with arm64 containers. Running intel containers with this qemu will be slow.

Running the intel version of qemu-system-aarch64 will be slow, as that runs via Rosetta and then emulates arm64 on top. So no matter what container arch you use it will be slow.

If you have an intel version of qemu-system-x86_64 you could run that via Rosetta and run the intel containers, and that will be closer to Intel Mac performance with intel containers. Running arm64 containers will be slow.

**Comment by rfay** [comment] 2022-03-30 17:55
If at all possible, you should run native (arm64 images with arm64 processor). This isn't just about performance, it's also about basic functionality. Some docker images won't work at all cross platform, and others have mysterious failures.

**Comment by cosygarcia** [comment] 2022-04-03 15:40
> @cosygarcia this [#204 (comment)](https://github.com/abiosoft/colima/issues/204#issuecomment-1083220386) is probably your situation. Your qemu version may be intel version utilising rosetta.

Yes I have checked. It is exactly the problem I have.
Qemu is running in "Intel mode". Iterm2 is running in "Apple mode".
I want to try to reinstall Colima but how to be sure that brew will reinstall the good version of Colima ?

**Comment by pedantic79** [comment] 2022-04-03 15:46
> I want to try to reinstall Colima but how to be sure that brew will reinstall the good version of Colima ?

The ARM version of brew installs into a different location. You can check with `brew shellenv`. 

```
dnn@Daniels-MBP ~ » brew shellenv
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
```
If your `HOMEBREW_PREFIX` is `/usr/local`, that's a good indication that all your packages installed are the Intel version and not the Arm version. You can also check this by running the `file` command and check the architecture.

```
dnn@Daniels-MBP ~ » file `which qemu-system-aarch64`
/opt/homebrew/bin/qemu-system-aarch64: Mach-O 64-bit executable arm64
```

**Comment by abiosoft** [comment] 2022-04-03 15:49
> Yes I have checked. It is exactly the problem I have. Qemu is running in "Intel mode". Iterm2 is running in "Apple mode". I want to try to reinstall Colima but how to be sure that brew will reinstall the good version of Colima ?

@cosygarcia I do not know precisely. If other brew installed apps are running in Intel mode, then a re-install of brew may be required.

Also, as mentioned here https://github.com/abiosoft/colima/issues/204#issuecomment-1083220386, older versions of Iterm2 run in Intel mode, you probably installed the apps (and brew) before Iterm2 was updated.

**Comment by abiosoft** [comment] 2022-05-03 14:24
I will be closing this as I think the issue is identified

**Closed by abiosoft** 2022-05-03 14:24 UTC

**Comment by maxyurk** [comment] 2023-06-25 09:06
for anyone else encountering this issue - what worked for me was to use VZ instead of QEMU:
```
colima start --vm-type=vz --cpu 6 --memory 8 --runtime containerd
```

**Comment by janaaronlee** [comment] 2023-08-15 07:09
@maxyurk no docker.sock is being generated when I use vz.

QEMU (default):
```
colima status
INFO[0000] colima is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] socket: unix:///~/.colima/default/docker.sock
```

VZ:
```
INFO[0000] colima is running using macOS Virtualization.Framework
INFO[0000] arch: aarch64
INFO[0000] runtime: containerd
INFO[0000] mountType: virtiofs
```
