### ISSUE TITLE
Disable Rosetta for VZ VM

### ISSUE THREAD

**Issue by Sangeppato** [abiosoft/colima#554] opened 2023-01-02 18:21 UTC
### Description

First of all, thank you for your amazing work.

It looks like Lima has some [performance issue](https://github.com/lima-vm/lima/issues/1269) when using VZ and Rosetta.
From my understanding, Rosetta is automatically enabled in Colima when VZ is used, with no way to manually disable it (the Lima overrides don't work).
Would you consider adding such an option?

**Comment by abiosoft** [comment] 2023-01-02 18:33
Yeah, definitely. We have no idea Rosetta has a negative effect.

**Comment by rfay** [comment] 2023-01-02 18:44
I would actually be in favor of rosetta being disabled by default. It has potential for enormous confusion, because wrong-arch binaries inside container might work or might not... It's amazing that it might be able to add value, but allowing it by default seems like a prescription for lots of impossible support requests.

**Comment by chadlwilson** [comment] 2023-01-03 02:10
FWIW, there might be an example (in part?) of such confusion at https://github.com/apple/swift/issues/62725 - note at the bottom sporadic rosetta errors (Virtualization.Framework / aarch64 / virtiofs). Unclear if the root cause was some Rosetta problem or Virtualization.Framework or virtiofs - lots of different variables :-)

**Comment by mapkon** [comment] 2023-01-03 02:17
Yeah, probably related. I moved the ticket here #539 - 

The issue disappeared when we switched to QEMU as opposed to MacOS.Virtualization.Framework. I am wondering if that is something that should be avoided at all costs.

@abiosoft Let me know if you need more information on that issue, or it will be addressed in this one.

**Closed** 2023-01-03 11:00 UTC
Labels: enhancement
